articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='article_list'),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

maintenance/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'maintenance'

urlpatterns = [
    url(r'^$', views.DeviceIndexView.as_view(), name='device_list'),
    url(r'^device/$', views.DeviceIndexView.as_view(), name='device_list'),
    path('<int:pk>/', views.DeviceDetailView.as_view(), name='device_details'),
    path('device/<int:pk>/maintenance/', views.DeviceMaintenanceView.as_view(), name='maintenance_by_device'),
    url(r'^maintenance/$', views.MaintenanceIndexView.as_view(), name='maintenance_list'),
    path('maintenance/<int:pk>/', views.MaintenanceDetailView.as_view(), name='maintenance_details'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('maintenance/', include('maintenance.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # add in thumbnail later
    # add in auther later

    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

# Create your models here.

maintenance/models.py
from django.db import models

# Create your models here.


class Device_type(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    def toString(self):
        return self.name.__str__

class Device(models.Model):  
    dev_type = models.ForeignKey(Device_type, on_delete=models.CASCADE)
    sn = models.CharField(max_length=100)
    # dev_id = models.CharField(max_length=100)
    manuf_date = models.DateTimeField(auto_now_add=True)
    descr = models.TextField()
    hw_ver = models.CharField(max_length=100)
    sw_ver = models.CharField(max_length=100)
    # add in thumbnail later
    # add in auther later

    def __str__(self):
        return self.dev_type.__str__() + '-' + self.sn
    
    def toString(self):
        return self.dev_type.__str__() + '-' + self.sn
    
    def dev_name_id(self):
        self.dev_id = self.dev_type.__str__() + '-' + self.sn
        return self.toString()

class Maintenance(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    received_at = models.DateTimeField(auto_now_add=False)
    repaired_at =  models.DateTimeField(auto_now_add=False)
    fault = models.TextField()
    description = models.TextField()
    comments = models.TextField()
    def __str__(self):
        return self.device.__str__() + ' - Fault: ' + self.fault + ' - ( ' + self.repaired_at.__str__() + ' ) ' 

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    #
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pud_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    #
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

articles/views.py
from django.shortcuts import render

# Create your views here.

def article_list(request):
    return render(request, 'articles/article_list.html')

homepage/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

def index(request):
    context = {
        'title': 'this is the title', 
        'header1': 'this is header one',
        }
    return render(request, 'homepage/index.html', context  )

maintenance/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic

from .models import Device, Maintenance

# Create your views here.

def device_list(request):
    return HttpResponse('Device List')
    # return render(request, 'articles/article_list.html')

class DeviceIndexView(generic.ListView):
    model = Device
    template_name = 'maintenance/device_list.html'
    context_object_name = 'device'

    def get_queryset(self):
            return Device.objects.all().order_by('dev_type', 'sn')

class DeviceDetailView(generic.DetailView):
    model = Device
    template_name = 'maintenance/device_details.html'
    context_object_name = 'device'

class MaintenanceIndexView(generic.ListView):
    model = Maintenance
    template_name = 'maintenance/maintenance_list.html'
    context_object_name = 'maintenance'

    def get_queryset(self):
        return Maintenance.objects.all().order_by('-repaired_at')

class MaintenanceDetailView(generic.DetailView):
    model = Maintenance
    template_name = 'maintenance/maintenance_details.html'
    context_object_name = 'maintenance'

class DeviceMaintenanceView(generic.ListView):
    model = Maintenance
    template_name = 'maintenance/maintenance_list_by_device.html'
    context_object_name = 'maintenance'
    def get_queryset(self):
        return Maintenance.objects.filter(device__id = self.kwargs['pk']).order_by('-repaired_at')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question
from django.http import HttpResponse


# Create your views here.



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

articles/templates/articles/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Articles</title>
</head>
<body>
    <h1>Article list</h1>
</body>
</html>

homepage/templates/homepage/index.html
<p>Start of Homepage</p>
<title>{{ title   | default:'Default title'   }}</title>
<h1>   {{ header1 | default:'Default header1' }}</h1>
<p>End of Homepage</p>

maintenance/templates/maintenance/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'maintenance/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet"  type="text/css" href="{% static 'maintenance/basic.css' %}">
    <!--Let browser know website is optimized for mobile-->


</head>


<body>
    <div id="sidebar">
        {% block sidebar %}

        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="content">
        {% block title %}{% endblock %}
    </div>

    <div id="content">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

maintenance/templates/maintenance/device_details.html
{% extends "maintenance/base.html" %}

{% load static %}

{% block title %}Device Details{% endblock %}

{% block body %}
    <h1> Name: {{ device.toString }} </h1>
    <h2> Type: {{ device.dev_type }}</h2>
    <p>{{device.dev_type.description}}</p>
    <h2> SN: {{ device.sn }}</h2>
    <h2> Description: </h2>
    <p>{{ device.descr }}s</p>
    <h2> HW Ver: {{ device.hw_ver }}</h2>
    <h2> SW Ver: {{ device.hw_ver }}</h2>
    <a href="{% url 'maintenance:maintenance_by_device' device.id %}">to device maintenance</a>
    <br>
    <a href="{% url 'maintenance:device_list' %}">to device list </a>
{% endblock %}

maintenance/templates/maintenance/device_list.html
{% extends "maintenance/base.html" %}

{% load static %}

{% block title %}Device list{% endblock %}

{% block body %}
    {% if device %}
        <ul>
        {% for device in object_list %}
            <li>
                <a href="{% url 'maintenance:device_details' device.id %}">{{ device.toString }}</a>
                <br><a href="{% url 'maintenance:maintenance_by_device' device.id %}">Maintenance</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No devices are available.</p>
    {% endif %}
    <a href="{% url 'maintenance:maintenance_list' %}">to maintenance list </a>
{% endblock %}

maintenance/templates/maintenance/maintenance_details.html
{% extends "maintenance/base.html" %}

{% load static %}

{% block title %}Maintenance Details{% endblock %}

{% block body %}
    <h1> {{ maintenance.device.toString }} </h1> 
    <h2> {{ maintenance.fault }}</h2>
    <h2> Received at: {{ maintenance.received_at.date }}</h2>
    <h2> Repaired at: {{ maintenamce.repaired_at.date }}</h2>
    <h2> Description: </h2>
    <p>{{ maintenance.description }}</p>
    <h2> Comments: </h2>
    <p>{{ maintenance.comments }}</p>

    <a href="{% url 'maintenance:maintenance_by_device' maintenance.device.id %}">to maintenance list for device {{ maintenance.device.toString }}</a>
    <br><a href="{% url 'maintenance:maintenance_list' %}">to maintenance list </a>
{% endblock %}

maintenance/templates/maintenance/maintenance_list.html
{% extends "maintenance/base.html" %}

{% block title %}Maintenance list{% endblock %}

{% block body %}
    {% if maintenance %}
        <ul>
        {% for maintenance in object_list %}
            <li>
                <a>{{ maintenance.repaired_at }}</a>
                <a href="{% url 'maintenance:device_details' maintenance.device.id %}">{{ maintenance.device }}</a>
                <br>Fault:<a href="{% url 'maintenance:maintenance_details' maintenance.id %}">{{ maintenance.fault }}</a>
                <br><a>Description: {{ maintenance.description }}</a>
                <br><a>Comments: {{ maintenance.comments }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No maintenances are available.</p>
    {% endif %}
    <br>
    <a href="{% url 'maintenance:device_list' %}">to device list </a>
{% endblock %} 

maintenance/templates/maintenance/maintenance_list_by_device.html
{% extends "maintenance/base.html" %}

{% block title %}
Maintenance list by device
{% endblock %}

{% block body %}
    {% if maintenance %}
        <ul></ul>
        {% for maintenance in object_list %}
            <li>
                <a>Repaired at: {{ maintenance.repaired_at.date }}</a>
                <br>
                <a>Device: </a>
                <a href="{% url 'maintenance:device_details' maintenance.device.id %}">{{ maintenance.device }}</a>
                <br><a>Fault: </a>
                <a href="{% url 'maintenance:maintenance_details' maintenance.id %}">{{ maintenance.fault }}</a>
                <br><a>Description: {{ maintenance.description }}</a>
                <br><a>Comments: {{ maintenance.comments }}</a>
            </li>
            <br>
        {% endfor %}
        </ul>
    {% else %}
        <p>No maintenances are available for device.</p>
    {% endif %}
    <a href="{% url 'maintenance:maintenance_list' %}">to maintenance list </a>
    <br>
    <a href="{% url 'maintenance:device_list' %}">to device list </a>
{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>